- .travis.yml
Here's the successful build that this change generated: https://travis-ci.org/cotsog/python-bluezero/builds/111303589
> .travis.yml file for dbus module on Python 2.7 & 3.2

- bluezero/peripheral.py
- Initial docstrings on peripheral.py's classes.  
- Removal of redundant class definitions.
- Some removal of redundant object assignments in Application.start()
> Documenting peripheral.py

- bluezero/adapter.py
- bluezero/peripheral.py
* Initial docstrings on adapter.py.
* Moved some of the global variables inside the Adapter class.
* Incorporated global constants references.
> Documenting adapter.py

- examples/iterate.py
- examples/microbit_button.py
Code used to demonstrate connecting to micro:bit
> microbit button demo

- bluezero/adapter.py
- bluezero/device.py
- tests/dbusmock_templates/bluezero.py
- tests/test_adapter.py
- tests/test_device.py
This seems to be breaking tests on Travis. These tests are working on local machine if ran individually. This is an issue with the tests and will need to be fixed. However I want to get the level 3 API in to the master
> Level 3 API for adapter & device

- bluezero/adapter.py
- bluezero/device.py
Also includes docstring adjustments for PEP8.
> minor updates for consistency between adapter.py and device.py

- bluezero/GATT.py
- bluezero/localGATT.py
- run_local_tests.sh
Tested with:
https://gist.github.com/ukBaz/0f3dd1747cae6cb18b1b477d84151f7a#file-peri
pheral_100-py
> Create local GATT service

- bluezero/tools.py
This might need  a better function name
> Find DBus object path for UUID

- bluezero/broadcaster.py
- bluezero/eddystone.py
First cut at a level 1 file for creating Eddystone beacon
> Eddystone Beacon

- bluezero/localGATT.py
- examples/level100/fatbeacon.py
Initial experiments with FatBeacon
https://github.com/google/physical-web/issues/814
> Physical-web FatBeacon

- docs/examples.rst
- docs/index.rst
- docs/install_bluez.rst
- docs/overview.rst
Various updates to reword explanations and remove references to the experimental flag.
> Documentation updates

- docs/install_bluez.rst
Not all BlueZ DBus API features are out from behind the experimental
flags so documenting this again
> Document experimental switch

- bluezero/localGATT.py
> add return values for charc and descs

- bluezero/localGATT.py
- examples/level100/blinkt_ble.py
fix for #81 and example script.
To be used in conjunction with this WebBluetooth UI: https://github.com/TheBubbleworks/BubblePy_Demo_Blinkt_BLE
> Blinkt 100 example

- .travis.yml
- README.rst
- bluezero/localGATT.py
- examples/level100/blinkt_ble.py
- examples/level100/cpu_temperature.py
- examples/level100/light_switch.py
- run_local_tests.sh
lightswitch.py
blinkt_ble.py
cpu_temperature.py
> New peripheral examples

- bluezero/GATT.py
There are still some empty argument docstrings and I'm not sure that I've got the description 100% correct for each class, but it's a starting point.
> more docstrings in GATT.py

- bluezero/microbit.py
> fixed typos of method name _pin_pwm_control

- bluezero/microbit.py
- bluezero/tools.py
- examples/bitbot_light.py
- examples/bitbot_line.py
Code to support Micro:bit robot from 4Tronix called bit:bot
> Support BitBot

- bluezero/GATT.py
- bluezero/microbit.py
- bluezero/tools.py
- docs/install_bluez.rst
- tests/test_gatt.py
Following major changes:
- New Local GATT Level 10 API
- New Microbit (Bitbot untested) level 1 API using the GATT Level 10 API
- New parent DBus class in tools
- Some updates to begin testing new features
> Proposed update to remote GATT API

- tests/test_gatt.py
Rename ngatt to GATT to allow the automated test to work.
> Fix GATT test

- .travis.yml
- README.rst
- examples/adapter_example.py
- run_local_tests.sh
- tests/test_adapter.py
- tests/test_adapter_example.py
- tests/test_advertisement.py
- tests/test_blinkt.py
- tests/test_broadcaster.py
- tests/test_device.py
- tests/test_eddystone.py
- tests/test_gatt.py
- tests/test_microbit.py
- tests/test_peripheral.py
The coverage is low still, however we can now see a more realistic
coverage number
> Add tests for all bluezero files

- docs/index.rst
- docs/tests.rst
- tests/test_adapter.py
Added docstrings for the adapter tests and updated the doc index to include developer notes and the adapter tests under a "developer" section.
> Doc updates for adapter tests

- docs/developer_docs.rst
- docs/index.rst
- docs/tests.rst
Contribution section needs further discussion, so omitting that from this change.
> Suggested developer doc updates

- .travis.yml
- bluezero/GATT.py
- bluezero/adapter.py
- bluezero/async_tools.py
- bluezero/central.py
- bluezero/dbus_tools.py
- bluezero/microbit.py
- bluezero/tools.py
- examples/adapter_example.py
- examples/async_example.py
- examples/commander.py
- run_local_tests.sh
- tests/test_async_tools.py
- tests/test_tools.py
4tronix is creating a new game controller style add-on for the microbit.
This adds support for that functionality.
This also adds better support for microbit IO Pin Service
This also adds better support for async/eventloop
> Add bit:commander support to microbit

- bluezero/microbit.py
Allow users to select which services are running on the micro:bit.
Also added the new micro:bit calibrate characteristic.
> Selectable bluetooth services

- bluezero/adapter.py
- bluezero/device.py
As we are supporting python 2.7 we need
to inherit from object to take advantage
of @property decorators.
> Added object inheritance

- .gitignore
- bluezero/microbit.py
Yes, but not immediately. I did not think that it was just a line in the comment block, first of all, I thought it was an error in the code, and after your comment, I was looking for a "docstring" file or documentation string that I need to change.
I tried following the developer-install notes, but it was occured error `Could not install packages due to an EnvironmentError: [WinError 5] Отказано в доступе: ` probably because, I use Windows, not Linux.
> Change docstring in microbit.py

- bluezero/dbus_tools.py
- bluezero/peripheral.py
python 3 uses bytes type. I add this type to send_notification_event . Tested same sw with python2/3 and seems to work properly
> add bytes type to send_notify_event

- bluezero/adapter.py
- bluezero/dbus_tools.py
- bluezero/peripheral.py
- bluezero/tools.py
I pass the macaddress(string) into connection/disconnection callback in order to understand who is.
> add on_connection/on_disconnection callbacks with device parameter

- bluezero/constants.py
- bluezero/mediaPlayer.py
Needed to play audio from my phone with a raspberry pi seems like it works really accurately with bluealsa-aplay and an external USB card, so i decided to give a shot and contribute at the same time since i want to use a python script. I made sure it was working correctly on my computer running on Debian.
> Added Bluetooth media player

- README.rst
> Improved Docs Update README.rst

- .github/workflows/python-app.yml
- bluezero/GATT.py
- bluezero/adapter.py
- bluezero/advertisement.py
- bluezero/dbus_tools.py
- bluezero/localGATT.py
- bluezero/media_player.py
- examples/control_media_player.py
- examples/cpu_temperature.py
- run_local_tests.sh
- tests/dbusmock_templates/bluez_scan.py
- tests/test_dbus_tools.py
- tests/test_peripheral_db_mock.py
> Tests for cpu_temperature example.

- bluezero/advertisement.py
- bluezero/broadcaster.py
- examples/manufacturer_data_beacon.py
Sets the manufacturer data in an advertisement. Added a call to this method also for beacons.
> Add Manufacturer Data to advertisement.

- examples/heartrate_monitor_central.py
- examples/heartrate_monitor_peripheral.py
As promised.  :)
Take a look at these, I'd love to update them and learn more about how you intended the library to be used and serve as "the defacto" examples for BLE.
For better or worse, a pair of scripts like this seems to accompany most Bluetooth implementations.  Now you've got them too.
> Add heartrate monitor examples for central and peripheral

- bluezero/dbus_tools.py
- bluezero/device.py
Catch DBus Exception for missing property
> Handle BLE device optional parameters

- bluezero/microbit.py
Adds the ability to  register a user callback for Micro:bit accelerometer notifications.
> Add microbit accelerometer subscription
