bluezero/peripheral.py, examples/toggle_services.py
Initial support for tearing down (stopping) an application and starting another one (perhaps with differnted services/advertisement) within the same Python script process.
Use case:  toggle between being a Physical Web beacon and a 'real' service.
Although this feature requires more testing and further dev it should not impact existing functionality. (other than adding a DBus visible ID being added to the object path to maintain uniqueness in the `/ukBaz/bluezero/` namespace)
=> Add peripheral.Application teardown support

bluezero/device.py, tests/test_device.py
If I got this right, removing the import of bluezero/tools (as per the fix for adapter) from `device.py` also fixes the device test.  (I also changed the alias that is set in the test so that it matches "Peripheral Device" - I hope I'm understanding it correctly!)
=> update to fix device dbusmock test

bluezero/GATT.py, bluezero/adapter.py, bluezero/advertisement.py, bluezero/device.py, bluezero/localGATT.py, bluezero/tools.py, examples/level100/cpu_temperature.py, tests/test_adapter.py, tests/test_device.py
In some modules GLib was being imported without a fallback to gobject which makes this not work with some older libraries.  I removed the import entirely from a couple files that were not using the mainloop.
=> Fallback import of GLib to gobject

examples/level100/blinkt_ble.py, examples/level100/cpu_temperature.py, examples/level100/light_switch.py
I'm slightly surprised it didn't fail it for lack of docstrings, but I guess different style checkers pick up on different things!
=> extra carriage return before main to pass pycodestyle.

bluezero/tools.py, tests/test_gatt.py
1. Updates to test_gatt  to match the newer dbusmock template
2. Add `object` as a parent of `DBusObject` for python 2 compatibility with GATT.py
=> Updates to fix GATT tests

.travis.yml, examples/bitbot_light.py, examples/bitbot_line.py, run_local_tests.sh, tests/obj_data.py, tests/test_adapter.py, tests/test_device.py, tests/test_gatt.py, tests/test_tools.py
There have been a number of issues with getting dbusmock working on Travis so have switched to using the mock library from Python unittest.
This change restricts the testing to Python3.6 currently.
However look at using https://pypi.python.org/pypi/mock/ so other versions can be used.
This should also enable code coverage reporting on:
https://codeclimate.com/github/ukBaz/python-bluezero
=> Switch from dbusmock to Python unittest.mock

.travis.yml, README.rst, bluezero/GATT.py, bluezero/adapter.py, bluezero/blinkt.py, bluezero/broadcaster.py, bluezero/central.py, bluezero/dbus_tools.py, bluezero/device.py, bluezero/microbit.py, bluezero/tools.py, examples/microbit_poll.py, run_local_tests.sh, tests/obj_data.py, tests/test_adapter.py, tests/test_advertisement.py, tests/test_blinkt.py, tests/test_central.py, tests/test_dbus_tools.py, tests/test_device.py, tests/test_microbit.py, tests/test_tools.py
This is quick a big change that breaks some of the existing API however
we are still pre 1.0.0 on this library and these are the kind of things
we are trying to get right before going to a fix release.
To aid this I’ve created the central.py file which has greatly
simplified the level 1 files like microbit.py and blinkt.py
closes #140 #138 #137
=> Squash DBus references to level 100 files only

docs/install_bluez.rst
Replace manual installation with `build-dep`.  As it might require some work in /etc/apt/sources.list, it may or may not actually be a useful change - but a shorter list of installation steps was appealing!
=> Simplify installation instructions

bluezero/adapter.py, bluezero/central.py, bluezero/dbus_tools.py
- Default adapter initialisation is broken because `list_adapters()` produces a path rather than an address.  This was the most straightforward way I could see of doing it, although if `list_adapters()` needs to change then that's the other way.
- This then needed tweaking in the Central initialisation for cases with no set adapter address.
- `get_props` in `dbus_tools` needed to have its output wrapped in a `get_dbus_obj` to match the expected value when linking to a callback.
=> Fix default Adapter Initialisation

bluezero/advertisement.py, bluezero/blinkt.py, bluezero/broadcaster.py, bluezero/eddystone.py, bluezero/microbit.py, bluezero/peripheral.py, docs/conf.py, docs/level1.rst, docs/shared.rst
The auto documentation of modules was not working on readthedocs
because the Bluezero modules were not loading because of missing
modules on the build server. This has been fixed by mocking the dbus
and gobject modules in the conf.py file.
Some tidy-up of docstrings. Mainly because __init__ strings are not
output
=> Mock dbus and gobject modules for readthedocs builds

examples/cpu_temperature.py
This fixes a bug where the example only worked when you did notify. If
you just did a read then it return a previously read value.
=> Get cpu temperature on read

bluezero/async_tools.py
This will catch an import error for gi.repository and use gobject instead, similar to the cpu_temperature.py example (https://github.com/ukBaz/python-bluezero/blob/master/examples/cpu_temperature.py).
=> Catch import error and using gobject as import

bluezero/observer.py
aioblescan made EddyStone a plugin and changed their referencing a bit. This fixes it for the EddyStone scanner example. Fixes bug #193.
=> Fix to work with latest aioblescan

bluezero/adapter.py
According to:
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt
Adapter1 interface has for attribute a list of UUIDs corresponding to the
physical device.
We here made this list available to the Adapter python class.
=> Add uuid attribute to Adapter

bluezero/device.py
According to
https://git.kernel.org/pubs/scm/bluetooth/bluez.git/tree/doc/device-api.txt
Device dbus object provides a method to pair and cancel pairing.
=> Add method to Pair device and cancel pairing

bluezero/peripheral.py
`peripheral.Characteristic.send_notify_event()` not worked when value is not str.
`peripheral.Characteristic.send_notify_event()` come to be able to accept list type argument.
=> Peripheral notifies of a not only string value.

bluezero/microbit.py
If I am not mistaken this code is not needed, as the same code is executed anyway while calling *central.Central.connect()*
=> microbit: don't load gatt twice

bluezero/microbit.py, examples/async_example.py
Tested with bluez 5.50
`subscribe_button_x` and `subscribe_pins` already invoke a response which does not contain the key `Value` (but a key `Notifying`). This results in an error in `subscribe_pins` (which expects a key `Value`) and gives an unexpected behaviour for the callback of `subscribe_button_x` because it is already invoked although not button was pressed.
This PR
- checks if a key `Value` is present, only then is the user callback invoked
- make changes so that user callback for `subscribe_button_x` receives the button status (0, 1, 2)
=> Change behaviour for subscribe_button_x and subscribe_pins

bluezero/dbus_tools.py, bluezero/device.py, tests/test_dbus_tools.py, tests/test_device.py
The error raising behavior of get_dbus path is not consistent, in fact:
In the case get_dbus_path is called with a correct adapter and
an erroneous device the function will silently return None.
In the case get_dbus_path is called with a correct device and an
erroneous adapter the function will raise a Value error because
_get_dbus_path is called with None on the second call.
Here we make the behavior uniform to allow better error management
where this function is used.
This change allows to uniformly return None when the dbus_path requested does not exist.
NEW APPROACH based on discussions in #246
=> dbus_tools: _get_dbus_path2 improvement

examples/ble_uart.py
Just spotted typo trying to use an example... not tested.
=> Fixed typo in name of constant

bluezero/dbus_tools.py, bluezero/device.py
After #285, I found a device in my environment that crashed bluezero because it had no name.   This provides for missing names.
=> provide for unnamed devices

bluezero/central.py, bluezero/device.py
This adds a timeout parameter to Device.connect and Central.connect .  Otherwise you wait 35 seconds until dbus gives up.
I wasn't sure how to handle the case of timing out.  For now it reraises the error even if it is from a timeout.
Additionally, I didn't add this to ConnectProfile because I don't have a profile to connect to, to test it, right now.
=> Timing out Connecting

bluezero/adapter.py, bluezero/dbus_tools.py, bluezero/peripheral.py, bluezero/tools.py, examples/ble_uart.py
Based on #324 . I added properties into peripheral so that the connection callbacks are more accessible.
I also modified dbus_tools.py to account for an issue where the address used in the bluez path does not match the public address of the device. In this case nothing could happen and an exception was thrown.
=> Expose on_connect and on_disconnect callbacks for the Peripheral

bluezero/observer.py
Trying to spin up some projects with TLM support. Bluezero is a great project but unfortunately lacks anything useful with Eddystone TLM data.
I have no clue what/if any other modifications are needed to the codebase to cleanly add TLM support but this at least works with the `eddystone_scanner.py` example.
=> observer: Add Eddystone TLM support

bluezero/localGATT.py, examples/peripheral_read_with_without_options.py
It is useful to have access to the options in a read callback, for example to get the device address.
For backward compatibility, this change first checks the signature of the callback, and only passes the options if the function has a parameter. This will allow existing code without options to continue working.
=> added ability to pass options into peripheral read callbacks

.github/workflows/pypi-publish.yml, .github/workflows/python-app.yml, bluezero/advertisement.py, docs/conf.py, docs/developer_docs.rst, docs/system_setup.rst, setup.py
=> Add capability to include tx power in advertisement
